client/src/components/Button/index.stories.tsx, client/src/components/Button/index.tsx
=> [FE] 프로젝트 디렉토리 구조 설계

client/package.json, client/pnpm-lock.yaml
=> [FE] lint staged dependency 설정 오류

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/youngcha/ohmycarset/OnBoardingActivity.kt, android/app/src/main/java/com/youngcha/ohmycarset/OnBoardingFirstFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/OnBoardingSecondFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/OnBoardingThirdFragment.kt, android/app/src/main/res/anim/fade_in.xml, android/app/src/main/res/anim/fade_out.xml, android/app/src/main/res/anim/slide_in_left.xml, android/app/src/main/res/anim/slide_in_right.xml, android/app/src/main/res/anim/slide_out_left.xml, android/app/src/main/res/anim/slide_out_right.xml, android/app/src/main/res/drawable/btn_mainstyle.xml, android/app/src/main/res/drawable/img_guide_mode.xml, android/app/src/main/res/layout/fragment_onboarding_page1.xml, android/app/src/main/res/layout/fragment_onboarding_page2.xml, android/app/src/main/res/layout/fragment_onboarding_page3.xml, android/app/src/main/res/layout/onboarding_activity.xml, android/app/src/main/res/navigation/onboarding_page.xml, android/app/src/main/res/values/strings.xml
=> [AOS] 온보딩 화면

client/plugins/pixel.js, client/tailwind.config.js
관련 이슈 #19 
pixel 플러그인 추가
- 현재 spacing, borderWidth, borderRadius, fontSize 속성에 pixel 단위 추가
- 추가로 필요한 속성이 있을 경우 변경 필요
Closed #19
=> [FE] Tailwind CSS 픽셀 단위 설정

server/build.gradle, server/src/main/java/com/youngcha/server/common/config/SwaggerConfig.java, server/src/main/java/com/youngcha/server/common/dto/ErrorResponse.java, server/src/main/java/com/youngcha/server/common/dto/SuccessResponse.java, server/src/main/java/com/youngcha/server/test/TestController.java, server/src/main/java/team/youngcha/config/SwaggerConfig.java, server/src/main/resources/application.yml, server/src/test/java/com/youngcha/server/test/TestIntegrationTest.java
close #22 
- Springdoc vs Springfox
- Springdoc이 최근까지 업데이트되었기 때문에 더 안정적으로 동작할 것이라 판단
- Swagger vs Spring rest docs
- Spring rest docs는 테스트를 해야 문서를 만들어준다. 테스트를 강제한다는 장점이 있지만, 사용이 불편하다. 두 가지를 동시에 사용하는 방법도 있지만, 테스트로 문서를 만드는 과정에 시간을 투자하기에는 여유롭지 않다고 판단해서 swagger 사용
=> [BE] Swagger 설정

client/package.json, client/plugins/typography.js, client/src/index.css, client/tailwind.config.js, client/tsconfig.json, client/vite.config.ts
closed #35 
1. 폰트 적용 안되는 것 수정
2. Import @ 절대경로 추가
=> [FE] tailwind 초기 설정 변경

.github/workflows/be-cd.yml, .github/workflows/be-ci.yml, .gitignore, server/.gitignore, server/Dockerfile, server/src/main/resources/application.yml
=> [BE] Backend CD 구축

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/youngcha/ohmycarset/ui/activity/MainActivity.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/customview/HeaderToolBar.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/interfaces/OnHeaderToolbarClickListener.kt, android/app/src/main/res/layout/activity_main.xml, android/app/src/main/res/layout/view_header_toolbar.xml, android/app/src/main/res/values/attrs.xml, android/app/src/main/res/values/themes.xml
=> [AOS] 공통 컴포넌트: 상단 툴바 구현

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/youngcha/ohmycarset/model/dialog/SwipeDialog.kt, android/app/src/main/java/com/youngcha/ohmycarset/model/dialog/TextDialog.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/adapter/dialog/SwipeAdapter.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/customview/SwipeDialogView.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/customview/TextDialogView.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/TrimSelectFragment.kt, android/app/src/main/res/drawable/dialog_background.xml, android/app/src/main/res/drawable/dialog_text_box.xml, android/app/src/main/res/layout/dialog_text.xml, android/app/src/main/res/layout/item_dialog_swipe.xml
close #76 
- 사용 방법
-     TextDialogView(requireContext(), TextDialog("파워 트레인", "디젤2.2", "높은 토크로 파워풀한 드라이빙이 가능하며,\n" +
"차급 대비 연비 효율이 우수합니다.\n" +
"높은 토크로 파워풀한 드라이빙이 가능하며,\n" +
"차급 대비 연비 효율이 우수합니다.\n" +
"차급 대비 연비 효율이 우수합니다.", "최고출력 202 ps / 2,800 rpm\n" +
"최대토크 45.0 kgf-
- 구현 화면
=> [AOS] 공통 컴포넌트: 텍스트 팝업창 구현

client/src/components/ProgressBar/ProgressItem.tsx, client/src/components/ProgressBar/SelectedBar.tsx, client/src/components/ProgressBar/index.stories.tsx, client/src/components/ProgressBar/index.tsx
프로그레스바 구현 #49 
하단에 움직이는 파란색 언더 바 - SelectedBar.tsx
- 언더 바 이동 transition tailwind 속성
```
ease-in-out duration-300
```
=> [FE] 프로그레스바 컴포넌트 구현

client/plugins/typography.js, client/src/index.css
스타일 관련 설정 오류를 수정하였습니다. 
closed #85
line-height 속성의 경우, % 단위 사용 불가
=> [FE] 스타일 관련 오류 수정

client/.gitignore, client/src/types/vite-env.d.ts, client/vite.config.ts
개발 환경 API 호출을 위한 proxy 설정
closed #69 
- Webpack으로 환경변수 파일 사용시, `process.env.REACT_APP_변수이름`으로 환경변수를 사용할 수 있습니다. 하지만 VITE 환경에서는 `import.meta.env.VITE_변수이름`으로 사용 가능합니다. 이 부분 참고하여 Data fetching 시에 작성하시면 됩니다.
=> [FE] Proxy 설정 및 개발 환경 URL 경로 설정

android/app/src/main/java/com/youngcha/ohmycarset/model/dialog/ButtonDialog.kt, android/app/src/main/java/com/youngcha/ohmycarset/model/dialog/ButtonHorizontal.kt, android/app/src/main/java/com/youngcha/ohmycarset/model/dialog/ButtonVertical.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/customview/ButtonDialogView.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/TrimSelectFragment.kt, android/app/src/main/res/drawable/style_active_blue_color_border.xml, android/app/src/main/res/drawable/style_hyundai_main_color_border.xml, android/app/src/main/res/drawable/style_sky_blue_color_border.xml, android/app/src/main/res/layout/dialog_button.xml, android/app/src/main/res/layout/item_dialog_swipe.xml, android/app/src/main/res/layout/layout_dialog_horizontal_button.xml, android/app/src/main/res/layout/layout_dialog_vertical_button.xml, android/app/src/main/res/values/colors.xml, android/app/src/main/res/values/strings.xml
closed #80
- 버튼 다이얼로그는 2종류(가로 배치, 세로 배치)가 있는데 따로 따로 만들려다 ButtonDialog 클래스에 type 변수를 추가하여 가로 배치 버튼인지 세로 배치 버튼인지에 따라 xml을 조작하는게 더 효율적이지 않나 해서 이러한 방식으로 구현했습니다. 이 부분에 대해서 어떻게 생각하세요??🤔 
- 사용법
- <pre>val dialog = ButtonDialogView(requireContext(), ButtonDialog("Vertical", R.drawable.ic_change, "모델을 변경하시겠어요?", ButtonHorizontal(
"", 1, "", ""), ButtonVertical("GuideMode")
))
dialog.setOnVerticalButtonClickListener { value ->
when (value) {
"SelfMode" -> {
view?.let { it1 -> Snackbar.make(it1, "SelfMode", Snackbar.LENGTH_SHORT).show() }
}
"GuideMode" -> {
view?.let { it1 -> Snackbar.make(it1, "GuideMode", Snackbar.LENGTH_SHORT).show() }
}
}
}
dialog.show() </pre>
- 구현 화면
| 가로 배치 | 세로 배치 |
|<img …
=> [AOS] 내 차 만들기 방식 변경 팝업창 구현 

client/src/components/MakingModeButton/GuideModeDetailList/index.tsx, client/src/index.css
관련 이슈 #91 
closed #91 
Tailwind CSS 관련 오류 수정
작업 브랜치에서는 발생하지 않은 오류였으나 merge 후 발생하였음.
정확한 원인은 추정이 되지 않으나, Tailwind CSS 내부의 동작 오류로 추정됨.
=> [FE] 내 차 만들기 모드 선택 버튼 오류 수정

.github/workflows/fe-cd.yml
프론트엔드 CD 설정 #94 
closed #94 
- dev/fe 브랜치에 push시 자동으로 build하여 s3로 업로드합니다.
- 테스트로 인해서 commit 내역이 중복으로 여러개 남아 squash merge로 merge 하겠습니다.
=> [FE] Frontend CD 설정

android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/LoadingFragment.kt, android/app/src/main/res/drawable/circle_progressbar.xml, android/app/src/main/res/drawable/ic_loading1.xml, android/app/src/main/res/drawable/ic_loading2.xml, android/app/src/main/res/drawable/ic_loading3.xml, android/app/src/main/res/layout/fragment_loading.xml, android/app/src/main/res/values/strings.xml
close #102 
- 우선, 프래그먼트 연결은 진행하지 않았습니다.
- 아래의 영상은 실행 결과 영상입니다.
- 3초 이후로는 현재 계속 반복되는 형태입니다.
https://github.com/softeerbootcamp-2nd/H8-YoungCha/assets/137713546/1873f112-0bc4-431c-9709-8a6015b7d85e
=> [AOS] 로딩 화면 구현

android/app/src/main/res/layout/dialog_dictionary.xml
=> [AOS] 백카사전 다이얼로그 레이아웃 구현

client/src/components/Header/index.tsx, client/src/components/layout/FullScreenLayout.tsx, client/src/index.css, client/src/pages/home/index.tsx, client/src/router/index.tsx
관련 이슈 #116 
FullScreenLayout 컴포넌트를 구현하였습니다.
closed #116 
- FullScreenLayout 구현
- 라우터 적용
- `/guide`
- `/making`
- 레이아웃 구현 PR과 conflict 발생할 수 있어 merge시 주의해야 합니다.
=> [FE] FullScreenLayout 컴포넌트 구현

server/src/main/java/team/youngcha/domain/option/controller/SelfOptionController.java, server/src/main/java/team/youngcha/domain/option/dto/FindGuideOptionResponse.java, server/src/main/java/team/youngcha/domain/option/dto/FindSelfOptionResponse.java, server/src/test/java/team/youngcha/IntegrationTestBase.java, server/src/test/java/team/youngcha/domain/option/GuideOptionIntegrationTest.java, server/src/test/java/team/youngcha/domain/option/SelfOptionIntegrationTest.java, server/src/test/resources/data/options_image.sql
=> [BE] Self mode 외장 색상 조회 API

android/app/src/main/java/com/youngcha/ohmycarset/ui/adapter/binding/BindingAdapter.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/adapter/viewpager/CarOptionPagerAdapter.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/customview/HeaderToolBarView.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/customview/HyundaiButtonView.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/CarCustomizationFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/viewmodel/CarCustomizationViewModel.kt, android/app/src/main/res/drawable/btn_unselect_style.xml, android/app/src/main/res/drawable/ic_check_guide.xml, android/app/src/main/res/drawable/shape_bottom_border_line.xml, android/app/src/main/res/drawable/shape_left_border_line.xml, android/app/src/main/res/drawable/shape_right_border_line.xml, android/app/src/main/res/drawable/shape_top_border_line.xml, android/app/src/main/res/drawable/style_guide_mode_button.xml, android/app/src/main/res/drawable/style_self_mode_button.xml, android/app/src/main/res/layout/fragment_car_customization.xml, android/app/src/main/res/layout/layout_estimate_summary.xml, android/app/src/main/res/layout/layout_hyundai_button.xml, android/app/src/main/res/values/attrs.xml
closed #108 
- 애니메이션 처리
-  뷰 클릭 시 발생하는 애니메이션 처리와 뷰모델 업데이트가 동시에 수행되다보니 애니메이션이 완료되기 전에 뷰모델의 변경 사항이 XML 뷰에 반영되어 애니메이션 동작이 중간에 끊기는 현상이 발생함. 이 부분에서 시간을 많이 씀... 해결 방법은 애니메이션 처리 함수인 animateBorder()가 ViewPropertyAnimator을 리턴하도록 하여 withEndAction을 사용하여 마지막 애니메이션이 완료된 후 뷰모델 업데이트를 수행하도록 변경함.
- 결과 화면
- <img src="https://github.com/softeerbootcamp-2nd/H8-YoungCha/assets/68272971/80956905-2232-41cb-8d4f-8ef65ac0e700" width="300" height="600">
=> [AOS] 내 차 만들기 - 가이드 모드 구현

client/src/hooks/useFetch.ts, client/src/service/index.ts
API 요청시 필요한 함수들을 구현하였습니다.
closed #159 
useFetch로는 data 상태를 수정하기 어려운 경우가 생겼습니다. 그래서 get 함수를 따로 사용해야 할 경우가 발생하여 분리 하였습니다.
일반적으로 useFetch hooks를 사용하되, 필요한 경우 get 함수를 따로 쓰시면 될것 같습니다!
=> [FE] API 요청 함수 구현

client/src/components/Transition/Transition.tsx
closed #111 
TailwindCSS 클래스를 사용하여 transition을 사용하는 컴포넌트를 구현했습니다. 
API는 주석을 참고해주시면 됩니다.
- base
- from
- to
- render
- unmount
=> [FE] Transition 컴포넌트 구현

server/src/main/java/team/youngcha/domain/estimate/repository/EstimateRepository.java, server/src/test/java/team/youngcha/domain/estimate/repository/EstimateRepositoryTest.java, server/src/test/java/team/youngcha/domain/option/GuideOptionIntegrationTest.java
Close #176
- sum(트림 + 옵션 + 키워드 포함) * 100 / sum(트림 + 옵션)이 아니라 sum(트림 + 옵션 + 키워드 포함) * 100 / sum(트림 + 키워드 포함)으로 계산
=> [BE] 키워드 비율 계산 수정

android/app/src/main/java/com/youngcha/ohmycarset/model/tag/Age.kt, android/app/src/main/java/com/youngcha/ohmycarset/model/tag/Gender.kt, android/app/src/main/java/com/youngcha/ohmycarset/model/tag/Important.kt, android/app/src/main/java/com/youngcha/ohmycarset/model/tag/Keyword.kt, android/app/src/main/java/com/youngcha/ohmycarset/model/tag/Strength.kt, android/app/src/main/java/com/youngcha/ohmycarset/model/tag/Tag.kt, android/app/src/main/java/com/youngcha/ohmycarset/model/tag/Use.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/adapter/recyclerview/AgeAdapter.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/adapter/recyclerview/GenderAdapter.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/adapter/recyclerview/ImportantAdapter.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/adapter/recyclerview/StrengthAdapter.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/adapter/recyclerview/UseAdapter.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/EstimateReadyFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/viewmodel/UserTagViewModel.kt, android/app/src/main/res/layout/layout_preliminaries_age.xml, android/app/src/main/res/layout/layout_preliminaries_gender.xml, android/app/src/main/res/layout/layout_preliminaries_keyword.xml, android/app/src/main/res/layout/preliminaries_long_button.xml, android/app/src/main/res/layout/preliminaries_short_button.xml
close #165
- bindingAdapter.kt 처리하는 부분이 아직 미숙해, 그 부분을 제외하고 데이터 바인딩 공부를 새로해 가이드 사전준비모드의 데이터 바인딩을 처리하였습니다.
- 화면 연결은 안해둔 상태이며, 이후 전체적인 화면 연결때, 작업하면 될 것 같습니다.
- 불필요한 구조가 있다면 편하게 피드백 부탁드립니다!
=> [AOS] 가이드 모드 사전조사 화면 데이터바인딩

server/src/main/java/team/youngcha/domain/car/repository/CarDetailsRepository.java, server/src/main/java/team/youngcha/domain/category/enums/RequiredCategory.java, server/src/main/java/team/youngcha/domain/estimate/repository/EstimateRepository.java, server/src/main/java/team/youngcha/domain/option/controller/GuideOptionController.java, server/src/main/java/team/youngcha/domain/option/controller/SelfOptionController.java, server/src/main/java/team/youngcha/domain/option/dto/FindSelfOptionResponse.java, server/src/main/java/team/youngcha/domain/option/enums/OptionType.java, server/src/main/java/team/youngcha/domain/option/repository/OptionRepository.java, server/src/main/java/team/youngcha/domain/option/service/OptionService.java, server/src/main/java/team/youngcha/domain/sell/repository/SellRepository.java, server/src/main/java/team/youngcha/domain/sell/repository/SellSelectiveOptionRepository.java, server/src/main/java/team/youngcha/domain/trim/service/TrimService.java, server/src/test/java/team/youngcha/domain/estimate/repository/EstimateRepositoryTest.java, server/src/test/java/team/youngcha/domain/option/SelfOptionIntegrationTest.java, server/src/test/java/team/youngcha/domain/option/repository/OptionRepositoryTest.java, server/src/test/java/team/youngcha/domain/option/service/OptionServiceTest.java, server/src/test/java/team/youngcha/domain/sell/repository/SellRepositoryTest.java
- Self mode 선택 옵션 조회 API 구현
- 응답 시간 측정 결과 38.86초 소요 (데이터 450만 건 기준)
- 테스트 추후 작성 예정
=> [BE] Self mode 선택 옵션 조회 API 

client/src/components/MakingModeButton/DetailCard.tsx, client/src/components/MakingModeButton/index.stories.tsx, client/src/components/MakingModeButton/index.tsx
action #15에서 발생한 빌드 시 타입 에러 수정
closed #187 
TrimType import 경로 수정
=> [FE] action #15 빌드 에러 수정 

server/build.gradle, server/docker-compose.local.yml, server/docker-compose.yml, server/script/deploy.sh, server/src/main/java/team/youngcha/common/config/RedisConfig.java, server/src/main/resources/application.yml, server/src/test/resources/application.yml
close #179 
- 캐시는 최대 1시간
- 캐시를 설정하고 싶은 메소드에 Cacheable 애노테이션을 달면 됩니다.
- 예시
```java
// key는 인자에 따라 다르게 캐시를 적용하고 싶을 때 사용
@Cacheable(value="category", key="#category.id")
public Category findCategory(Category category) {
}
```
=> [BE] Redis 설정

server/src/main/java/team/youngcha/domain/keyword/enums/KeywordName.java, server/src/main/java/team/youngcha/domain/keyword/repository/KeywordRepository.java, server/src/main/java/team/youngcha/domain/option/controller/GuideOptionController.java, server/src/main/java/team/youngcha/domain/option/repository/OptionRepository.java, server/src/main/java/team/youngcha/domain/option/service/OptionService.java, server/src/main/java/team/youngcha/domain/sell/repository/SellRepository.java
가이드 모드 휠 조회 API 구현
close #185 
- 가이드 모드 휠 조회 API 구현
- 사용자가 선택한 키워드에 해당하는 모든 휠 옵션을 조회
- 추천 방법
- 사용자가 '디자인' 키워드를 선택한 경우
- i) '안전성' 혹은 '주행' 키워드도 선택한 경우 : '알콘(alcon) 단조 브레이크 & 20인치 블랙톤 전면 가공 휠' 추천
- ii) 그 외 : 사용자가 선택한 트림과 외장색상을 기준으로 다음의 휠 중 더 많이 판매된 것을 추천
- '20인치 블랙톤 전면 가공 휠' 혹은 '20인치 다크 스퍼터링 휠'
- 사용자가 '디자인' 키워드를 선택하지 않은 경우 : '20인치 알로이 휠 & 타이어' 추천
- 테스트 미작성, 추후 작성 예정
- 응답 시간 측정 결과 : 4초 소요
=> [BE] 가이드 모드 휠 조회 API

android/app/src/main/java/com/youngcha/ohmycarset/model/car/OptionInfo.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/customview/FeedbackView.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/CarCustomizationFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/EstimateReadyFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/LoadingFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/TrimSelectFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/util/AnimationUtils.kt, android/app/src/main/java/com/youngcha/ohmycarset/viewmodel/CarCustomizationViewModel.kt, android/app/src/main/res/layout/fragment_car_customization.xml, android/app/src/main/res/layout/item_estimate_summary.xml, android/app/src/main/res/layout/layout_estimate.xml, android/app/src/main/res/layout/layout_feed_back.xml, android/app/src/main/res/layout/layout_hyundai_button.xml, android/app/src/main/res/navigation/nav_graph.xml
closed #195 
- 빵빠레, 금액 애니메이션 모두 util/AnimationUtils 에 두었습니다.
- 결과 화면
- 
| 빵빠레 | 피드백 & 전체 금액|
|:------:|:-----:|
| <img src="https://github.com/softeerbootcamp-2nd/H8-YoungCha/assets/68272971/2f0eea48-df16-4acf-adbe-7956eb2ea992" width="300" height="500"/> | <img src="https://github.com/softeerbootcamp-2nd/H8-YoungCha/assets/68272971/23af46c4-a7d4-41a6-9fa7-c4afe828a4bf" width="300" height="500"/> |
=> [AOS] 애니메이션 추가 구현

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/youngcha/ohmycarset/model/Dictionary.kt, android/app/src/main/java/com/youngcha/ohmycarset/model/TrimMainData.kt, android/app/src/main/java/com/youngcha/ohmycarset/repository/ApiService.kt, android/app/src/main/java/com/youngcha/ohmycarset/repository/RetrofitClient.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/activity/MainActivity.kt
=> [AOS] 메인 페이지 API 연결

client/src/App.tsx, client/src/assets/icons/model-change-arrow.tsx, client/src/components/Button/index.tsx, client/src/components/Header/DictionaryToggleButton.tsx, client/src/components/Header/ModeChangeButton.tsx, client/src/components/Header/ModeChangeModal.tsx, client/src/components/Header/index.tsx, client/src/components/PopUp/Contents/ModeSelectCard.tsx, client/src/components/PopUp/Contents/PopUpButton.tsx, client/src/components/PopUp/index.tsx, client/src/components/ProgressBar/index.stories.tsx, client/src/components/ProgressBar/index.tsx, client/src/pages/home/index.tsx, client/src/pages/making/index.tsx, client/src/pages/making/select/SelectOptionPage.tsx, client/src/types/index.ts
옵션 변경 시 팝업 띄우기
closed #196 
https://github.com/softeerbootcamp-2nd/H8-YoungCha/assets/37887690/3d92ac06-39d3-48c7-91d6-97808d69a331
=> [FE] 헤더 옵션 변경 팝업 추가

.github/workflows/fe-ci.yml
CI 할 시 빌드 체크 깃 액션 추가
closed #223
=> [FE] CI 추가 적용

android/app/src/main/java/com/youngcha/ohmycarset/ui/customview/HyundaiButtonView.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/CarCustomizationFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/LoadingFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/TrimSelectFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/viewmodel/CarCustomizationViewModel.kt, android/app/src/main/res/layout/fragment_loading.xml, android/app/src/main/res/layout/layout_estimate_ready.xml, android/app/src/main/res/navigation/nav_graph.xml
=> [AOS] 화면 플로우 수정 

server/src/main/java/team/youngcha/domain/estimate/repository/EstimateRepository.java, server/src/main/java/team/youngcha/domain/option/controller/GuideOptionController.java, server/src/main/java/team/youngcha/domain/option/repository/OptionRepository.java, server/src/main/java/team/youngcha/domain/option/service/OptionService.java, server/src/main/java/team/youngcha/domain/sell/repository/SellRepository.java, server/src/test/java/team/youngcha/domain/option/repository/OptionRepositoryTest.java, server/src/test/java/team/youngcha/domain/option/service/OptionServiceTest.java
관련이슈 #237 
- sell 쿼리를 쓰게되면 속도가 느려져서 성능 향상을 위해, 유사 사용자를 기준으로 추천해주도록 변경
=> [BE] 휠 가이드 모드 선택 수정

server/src/main/java/team/youngcha/common/config/RedisConfig.java, server/src/main/java/team/youngcha/domain/estimate/repository/EstimateRepository.java, server/src/test/resources/schema.sql
관련이슈 #241 , .....
- power train, driving system, body type, wheel의 경우 캐시가 되지 않으면 1초, 되어 있으면 0.5초 이하로 동작
- 해당 쿼리에 index 적용 (keyword1, keyword2, keyword3, gender, ageRange, trim)
```Java
String sql = "select estimate." + optionIdColumn + ", COUNT(*) as count from estimate " +
"where estimate.keyword1_id in (:keywords) " +
"and estimate.keyword2_id in (:keywords) " +
"and estimate.keyword3_id in (:keywords) ";
if (!Objects.equals(category.getName(), RequiredCategory.WHEEL.getName())) {
params.addValue("gender", guideInfo.getGender().getType());
params.addValue("ageRange", guideInfo.getAgeRange().getRange());
sql += "and estimate.age_range = (:ageRange) " +
"and estimate.gender = (:gender) ";
}
sql += "and estimate.trim_id = (:trimId) " +
"and …
```
=> [BE] Guide mode 필수 선택 옵션 api 속도 개선

client/src/components/Button/index.tsx, client/src/pages/guide/MoveButtonBox.tsx, client/src/pages/guide/PrepareGuide.tsx, client/src/pages/guide/SelectButtonsBox/AgeSelectButtonsBox.tsx, client/src/pages/guide/SelectButtonsBox/GenderSelectButtonsBox.tsx, client/src/pages/guide/SelectButtonsBox/KeywordButton.tsx, client/src/pages/guide/SelectButtonsBox/KeywordSelectButtonsBox.tsx, client/src/pages/guide/TitleBox.tsx, client/src/pages/guide/type.ts, client/src/store/useTagSelectContext.tsx
관련 이슈 #171 
closed #171 
https://github.com/softeerbootcamp-2nd/H8-YoungCha/assets/80496795/0b1b1432-aa40-435d-b09e-a47b903323b3
=> [FE] 가이드 모드 태그 선택값 저장

server/src/main/java/team/youngcha/domain/car/dto/CarDetails.java, server/src/main/java/team/youngcha/domain/car/dto/CarResponse.java, server/src/main/java/team/youngcha/domain/car/dto/FindCarDetailsResponse.java, server/src/main/java/team/youngcha/domain/car/dto/GuideModeDetails.java, server/src/main/java/team/youngcha/domain/car/dto/ModelName.java, server/src/main/java/team/youngcha/domain/car/entity/Car.java, server/src/main/java/team/youngcha/domain/car/repository/CarDetailsRepository.java, server/src/main/java/team/youngcha/domain/car/repository/CarRepository.java, server/src/main/java/team/youngcha/domain/car/service/CarService.java, server/src/main/java/team/youngcha/domain/trim/service/TrimService.java, server/src/main/resources/schema.sql, server/src/test/java/team/youngcha/domain/car/FindCarDetailsIntegrationTest.java, server/src/test/java/team/youngcha/domain/car/FindCarsIntegrationTest.java, server/src/test/java/team/youngcha/domain/car/repository/CarDetailsRepositoryTest.java, server/src/test/java/team/youngcha/domain/car/repository/CarRepositoryTest.java, server/src/test/java/team/youngcha/domain/car/service/CarServiceTest.java, server/src/test/java/team/youngcha/domain/option/repository/OptionRepositoryTest.java, server/src/test/java/team/youngcha/domain/sell/repository/SellRepositoryTest.java, server/src/test/java/team/youngcha/domain/trim/service/TrimServiceTest.java, server/src/test/resources/data/car.sql, server/src/test/resources/data/car_details.sql
close #246
API 명세 수정으로 인한 자동차 상세정보 조회 기능 추가 및 변경
- 가이드 모드 정보를 트림 정보와 분리하여 별도의 항목으로 응답
- 자동차 영문 이름 제공
=> [BE] 자동차 상세정보 조회 기능 수정

server/src/main/java/team/youngcha/common/enums/AgeRange.java, server/src/main/java/team/youngcha/domain/sell/repository/SellRepository.java, server/src/main/java/team/youngcha/domain/sell/repository/SellSelectiveOptionRepository.java
관련이슈 #249 , .....
- 인덱스 생성
- 범위절을 in 절로 바꿔서 다른 조건도 인덱스를 탈 수 있도록 수정
인덱스 사용 (6초 -> 0.36초)
=> [BE] Guide mode 색상 선택 API 속도 개선

server/src/main/java/team/youngcha/domain/option/repository/OptionRepository.java, server/src/main/java/team/youngcha/domain/trim/service/TrimService.java
close #255 
트림 기본 품목 전체 카테고리 조회 기능 추가
=> [BE] 트림 기본 품목 조회 기능 추가

server/src/main/java/team/youngcha/domain/car/repository/CarDetailsRepository.java, server/src/main/java/team/youngcha/domain/option/enums/OptionType.java, server/src/main/java/team/youngcha/domain/option/repository/OptionRepository.java, server/src/test/java/team/youngcha/domain/option/repository/OptionRepositoryTest.java
close #260
트림 기본 품목 조회 시 아이콘 이미지가 조회되는 오류 해결
=> [BE] 트림 기본 품목 조회 시 아이콘 이미지가 조회되는 오류

server/src/main/java/team/youngcha/common/config/CustomSerializer.java, server/src/main/java/team/youngcha/common/config/RedisConfig.java, server/src/main/java/team/youngcha/domain/estimate/repository/EstimateRepository.java, server/src/main/java/team/youngcha/domain/option/service/OptionService.java, server/src/main/java/team/youngcha/domain/sell/repository/SellRepository.java, server/src/main/java/team/youngcha/domain/sell/repository/SellSelectiveOptionRepository.java
관련이슈 #254 
아무리 줄여도 최대 10초 가량 나온다.
캐시가 답이다.
=> [BE] Guide mode 선택 옵션 API 개선

server/src/main/java/team/youngcha/common/config/RedisConfig.java
=> [BE] Redis 만료 기한 수정

client/package.json, client/pnpm-lock.yaml, client/src/App.tsx, client/src/components/MakingModeButton/index.tsx, client/src/components/OptionCard/AdditionalContents/SummarySection.tsx, client/src/components/OptionCard/Name.tsx, client/src/components/OptionCard/index.tsx, client/src/constant.ts, client/src/pages/home/BasicOptionBox.tsx, client/src/pages/home/BasicOptionLists.tsx, client/src/pages/home/CarsImageBox.tsx, client/src/pages/home/FirstScreenBox.tsx, client/src/pages/home/HomePage.tsx, client/src/pages/home/MakingCarButtonsBox.tsx, client/src/pages/home/TrimCardsBox.tsx, client/src/pages/home/index.tsx, client/src/pages/home/type.ts, client/src/pages/making/constant.ts, client/src/pages/making/select/SelectOptionMessage.tsx, client/src/router/index.tsx, client/src/types/dictionary.ts, client/src/types/index.ts, client/src/utils/getNewOptionData.ts
- 백카사전 기능 추가 및 로직 변경 적용
- 메인페이지 UI 수정
closed #256 
백카사전의 경우 absoulte를 사용시 모달 짤림 현상이 발생하여 fixed를 사용하여 해결하였습니다.
비록 스크롤 및 화면 사이즈가 동적으로 변할 시 버그가 있지만 이후 더 나은 방식으로 해결하겠습니다.
=> [FE] 백카사전 기능 추가 및 로직 변경 적용

client/src/components/Confetti/index.tsx
closed #272
confetti 사용 페이지에서 다른 페이지로 이동할 시 console에 발생하는 error를 해결하였습니다.
=> [FE] Confetti 오류 수정

android/app/src/main/java/com/youngcha/ohmycarset/data/api/BaekcasajeonApiService.kt, android/app/src/main/java/com/youngcha/ohmycarset/data/api/RetrofitClient.kt, android/app/src/main/java/com/youngcha/ohmycarset/data/dto/BaekcasajeonDTO.kt, android/app/src/main/java/com/youngcha/ohmycarset/data/dto/DataXXX.kt, android/app/src/main/java/com/youngcha/ohmycarset/data/model/Baekcasajeon.kt, android/app/src/main/java/com/youngcha/ohmycarset/data/repository/BaekcasajeonRepository.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/activity/MainActivity.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/customview/BaekcasajeonDialogView.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/customview/HeaderToolBarView.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/CarCustomizationFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/TrimSelectFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/util/ViewExtensions.kt, android/app/src/main/java/com/youngcha/ohmycarset/viewmodel/BaekcasajeonViewModel.kt, android/app/src/main/java/com/youngcha/ohmycarset/viewmodel/TrimSelectViewModel.kt, android/app/src/main/java/com/youngcha/ohmycarset/viewmodel/factory/BaekcasajeonFactory.kt, android/app/src/main/res/layout/dialog_baekcasajeon.xml, android/app/src/main/res/layout/fragment_car_customization.xml, android/app/src/main/res/layout/fragment_trim_select.xml, android/app/src/main/res/layout/view_header_toolbar.xml
closed #286 
- <img src="https://github.com/softeerbootcamp-2nd/H8-YoungCha/assets/68272971/8ed8c27c-f65a-4375-af28-b450f8b86ed1" width="300" height="500"/>
=> [AOS] 백카사전 기능 구현

android/app/src/main/java/com/youngcha/ohmycarset/ui/customview/HyundaiButtonView.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/CarCustomizationFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/TrimSelectFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/util/TextViewExtensions.kt, android/app/src/main/res/layout/fragment_car_customization.xml, android/app/src/main/res/layout/fragment_trim_select.xml, android/app/src/main/res/layout/view_header_toolbar.xml
closed #299 
- 내 차 만들기 자세히 보기 브랜치를 만들어놨었는데... 모르고 새로운 브랜치를 만들었네요..🤦 기존 브랜치에서 이어서 작업하겠습니다.
=> [AOS] 내 차 만들기 자세히 보기 커스텀 다이얼로그 연결 #299

.github/workflows/fe-cd.yml
관련이슈 #309 
프론트엔드 배포시 바로 적용이 되지 않는 문제를 수정하였습니다.
=> [FE] 프론트엔드 CD 수정

client/src/components/FeedbackCard/index.tsx, client/src/components/OptionCard/Rate.tsx, client/src/components/OptionCard/Skeleton.tsx, client/src/components/OptionCard/index.tsx, client/src/index.css, client/src/pages/making/select/SelectMultiOptionPage.tsx, client/src/pages/making/select/SelectOptionPage.tsx, client/src/types/option.ts, client/tailwind.config.js
closed #289 
가이드 모드에서 추천 옵션 선택시 테두리가 그려지는 옵션 카드의 애니메이션을 구현합니다.
index.css 내부에 키프레임과 애니메이션을 추가했습니다.
=> [FE] 가이드 모드 옵션 카드 애니메이션 구현

client/package.json, client/pnpm-lock.yaml, client/src/App.tsx, client/src/components/Header/HeaderPopUp/ExitPopUp.tsx, client/src/components/OptionCard/Name.tsx, client/src/components/RotateCarImage/index.tsx, client/src/components/SummaryModal/index.tsx, client/src/hooks/useAnimatedPrice.ts, client/src/hooks/useSelectOption.ts, client/src/pages/making/complete/CompleteOptionPage.tsx, client/src/pages/making/constant.ts, client/src/pages/making/detail-option-box/DetailSelectOptionBox.tsx, client/src/pages/making/index.tsx, client/src/pages/making/select/SelectMultiOptionPage.tsx, client/src/pages/making/select/SelectOptionFooter.tsx, client/src/pages/making/select/SelectOptionPage.tsx, client/src/store/useUserSelectedOptionContext.tsx, client/src/utils/getRotateImages.ts
선택 옵션 카드 데이터 연동 및 버그 수정
closed #280 
데이터 관련  버그들이 많아 수정하였습니다. 혹시 발견하시면 코멘트 부탁 드립니다.
=> [FE] 선택 옵션 카드 데이터 연동

android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/EstimateReadyFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/viewmodel/UserTagViewModel.kt
=> [AOS] 가이드모드 사전 준비 키워드 오류

android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/CarCustomizationFragment.kt, android/app/src/main/java/com/youngcha/ohmycarset/ui/fragment/EstimateReadyFragment.kt
=> [AOS] 최종 수정
